### ISSUE TITLE
Working in progress

### ISSUE THREAD

**Issue by alce65** [mireyachaparro/202210-w3ch5-mireya-chaparro#1]
Llevamos unos 2/3 del challenge y apenas has subido nada después del "Initial commit".
Si has podido hacer algo, recuerda que la rama con la feature en la que estemos trabajando se sube a remoto en cuanto tiene algún contenido. No hay que esperar a que este lista para la PR. De esta forma estamos salvaguardando nuestro trabajo en Github, por si acaso pasara algo en local
La idea de los fines de semana no es repasar, sino poner en práctica y de esa forma adquirir los conocimientos. Si no, los planteamientos del bootcamp pierden sentido. Aunque no entiendas muchas cosas tienes que tratar de poner en practica algunas. Espero que puedas hacerlo a lo largo de hoy.

**Comment by mireyachaparro** [comment]
gracias alejandro, en cuanto lo vi, hice commits cada x tiempo, no volvera a pasar
